export const ADD_TASK = 'ADD_TASK';
export const GET_ALL_PERSISTED_TASKS = 'GET_ALL_PERSISTED_TASKS';
export const DELETE_TASK = 'DELETE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const CLEAR_TASKS = 'CLEAR_TASKS';
export const PERSIST_ALL_TASKS = 'PERSIST_ALL_TASKS';