export const ADD_TASK = 'ADD_TASK';
export const ADD_MULTIPLE_TASKS = 'ADD_MULTIPLE_TASKS';
export const GET_ALL_PERSISTED_TASKS = 'GET_ALL_PERSISTED_TASKS';
export const DELETE_TASK = 'DELETE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const CLEAR_TASKS = 'CLEAR_TASKS';