import React, { useState, useRef } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { addTask as addTaskService } from '../Utilities/services';
import { addTask, editTask, getTasks, deleteTasks, persistAllTasks } from '../Store/Reducers/tasksActions';
import { images } from '../Utilities/URLs';

const messages = [
    {
        id: 1,
        creationDate: new Date().toLocaleDateString(),
        heading: 'Brunch this week?',
        description: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
        imageUrl: images["url_1"],
    },
    {
        id: 2,
        creationDate: new Date().toLocaleDateString(),
        heading: 'Birthday Gift',
        description: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
        imageUrl: images["url_2"],
    },
    {
        id: 3,
        creationDate: new Date().toLocaleDateString(),
        heading: 'Recipe to try',
        description: 'I am try out this new BBQ recipe, I think this might be amazing',
        imageUrl: images["url_3"],
    },
    {
        id: 4,
        creationDate: new Date().toLocaleDateString(),
        heading: 'Yes!',
        description: 'I have the tickets to the ReactConf for this year.',
        imageUrl: images["url_4"],
    },
    {
        id: 5,
        heading: "Doctor's Appointment",
        creationDate: new Date().toLocaleDateString(),
        description: 'My appointment for the doctor was rescheduled for next Saturday.',
        imageUrl: images["url_5"],
    },
    {
        id: 6,
        heading: 'Discussion',
        creationDate: new Date().toLocaleDateString(),
        description: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
        imageUrl: images["url_6"],
    },
    {
        id: 7,
        heading: 'Summer BBQ',
        creationDate: new Date().toLocaleDateString(),
        description: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
        imageUrl: images["url_1"],
    },
    {
        id: 8,
        heading: "Doctor's Appointment",
        creationDate: new Date().toLocaleDateString(),
        description: 'My appointment for the doctor was rescheduled for next Saturday.',
        imageUrl: images["url_5"],
    },
    {
        id: 9,
        heading: 'Discussion',
        creationDate: new Date().toLocaleDateString(),
        description: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
        imageUrl: images["url_6"],
    },
    {
        id: 10,
        heading: 'Summer BBQ',
        creationDate: new Date().toLocaleDateString(),
        description: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
        imageUrl: images["url_1"],
    },
    {
        id: 11,
        heading: 'Brunch this week?',
        creationDate: new Date().toLocaleDateString(),
        description: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
        imageUrl: images["url_1"],
    },
    {
        id: 12,
        heading: 'Birthday Gift',
        creationDate: new Date().toLocaleDateString(),
        description: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
        imageUrl: images["url_2"],
    },
    {
        id: 13,
        heading: 'Recipe to try',
        creationDate: new Date().toLocaleDateString(),
        description: 'I am try out this new BBQ recipe, I think this might be amazing',
        imageUrl: images["url_3"],
    },
    {
        id: 14,
        heading: 'Yes!',
        creationDate: new Date().toLocaleDateString(),
        description: 'I have the tickets to the ReactConf for this year.',
        imageUrl: images["url_4"],
    },
    {
        id: 15,
        heading: "Doctor's Appointment",
        creationDate: new Date().toLocaleDateString(),
        description: 'My appointment for the doctor was rescheduled for next Saturday.',
        imageUrl: images["url_5"],
    },
    {
        id: 16,
        heading: 'Discussion',
        creationDate: new Date().toLocaleDateString(),
        description: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
        imageUrl: images["url_6"],
    },
];

const useInit = () => {
    let initialize = JSON.parse(localStorage.getItem("initCounter"));
    const dispatch = useDispatch();
    const [saveMsg, setSaveMsg] = useState("");
    let successfulUploads = [];
    let erroredUploads = [];
    if (+initialize == 0) {
        console.log(initialize, 'initialize value')
        messages.forEach((message) => {
            dispatch(addTask(message));
            addTaskService(message, (id_or_err, type) => {
                if (type == 'success') {
                    successfulUploads.push({ firebaseId: id_or_err, id: message.id });
                }
                else if (type == 'error') {
                    erroredUploads.push({ errorMsg: id_or_err, id: message.id })
                }
            });
        });
        dispatch(persistAllTasks);

        if (messages.length == successfulUploads.length) {
            setSaveMsg("Successfully Uploaded all " + messages.length + " tasks.");
        }
        else if (erroredUploads.length && successfulUploads.length) {
            setSaveMsg("Few tasks failed to upload on firebase DB " + erroredUploads)
        }
        else {
            setSaveMsg("All Initial Task Uploads Failed.");
        }

        localStorage.setItem("initCounter", JSON.stringify(1));
    }

    return {
        saveMsg
    }
}

export default useInit;